name: Bicep IAC Pipeline
on: workflow_dispatch
jobs:
  self-hosted-runner:
    runs-on: [self-hosted, gpu, linux]
    steps:
    - name: run-me-inside-self-hosted-runner
      run: |
         echo "This job is running on a self-hosted runner!"

    - name: sleep for 100 seconds
      run: sleep 100